@extends('layouts.app')

@section('head')
    <style>
        h3 {
            margin-top: 30px;
            margin-bottom: 0;
        }
    </style>
@endsection

@section('content')
    <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
        <div class="separator separator-bottom separator-skew zindex-100">
            <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
                <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
            </svg>
        </div>
    </div>
    <!-- Page content -->
    <div class="container mt--8 pb-5">
        <div class="card bg-secondary border-0 mb-0">
            <div class="card-body px-lg-5 py-lg-5" style="white-space: pre-line;">
                <h1>Privacy Policy</h1>
                This privacy policy (“Policy”) applies to https://www.CombineSell.com/ (“Site”) and the CombineSell branded and related products and services that are owned and operated by CombineSell.com Pte. Ltd., a Singapore limited liability company (“CombineSell”). This policy tells you how personal information is collected, used, disclosed, and protected by CombineSell.<br />
                <h3>Information Collected</h3>
                We collect information from you in various ways when you use our Site and services. We may also supplement this information with information from other companies. We collect two general types of information, namely personal information and aggregate data. As used in this Policy, the term “personal information” means information that specifically identifies an individual (such as a name and email address), and demographic and other information when directly linked to information that can identify an individual.<br />
                Our definition of personal information does not include “aggregate” data. Aggregate data is information we collect about a group or category of services or users from which individual user identities have been removed. In other words, no personal information is included in aggregate data. Aggregate data helps us understand trends in our users’ needs so that we can better consider new features or otherwise tailor our services. This Policy in no way restricts or limits our collection and use of aggregate data, and we may share aggregate data about our users with third parties for various purposes, including to help us better understand our customer needs and improve our services and for advertising and marketing purposes.<br />
                The following are the specific types of information we collect from you.<br />
                Information You Give Us. We collect information you give us on our Site and when you register for and use our services. Examples include the following:<br />
                Registration and Profile Information. When you register to use our services or update your profile, we may collect various kinds of information about you including, your name and email address; your title, company and other profile information you provide; demographic information; and information you upload like photos, files, and documents.<br />
                Payment Information. If you choose to use a paid CombineSell account or service, our payment processing vendor collects your credit card information and billing address.<br />
                Third-Party Account Information. When you connect our services to your marketplace accounts on third-party websites, we collect the login and authentication information necessary to maintain the connection, as well as any information downloaded from these third-party websites, such as order and inventory information.<br />
                Submissions and Customer Service. From time to time we may use surveys, contests or sweepstakes requesting personal or demographic information and customer feedback.<br />
                Automatically Collected Information. We automatically receive certain types of information when you interact with our Site, services and communications. For example, it is standard for your Web browser to automatically send information to every Web site you visit, including ours. That information includes your computer’s IP address, access times, your browser type and language, and referring Web site addresses. We may also collect information about the type of operating system you use, your account activity, and files and pages accessed or used by you.<br />
                Cookies and Web Beacons. We may also use certain kinds of technology such as cookies and Web beacons to collect information. Among other things, the use of cookies and Web beacons enables us to improve our Web sites and emails by seeing which areas and features are most popular, to count the number of computers accessing our Web site, to personalize and improve your experience, to record your preferences, and to allow you to visit our Web site without re- entering your member ID and/or password. A cookie is a small amount of data which is sent to your browser from a Web site’s computers and stored on your computer’s hard drive. Most browsers automatically accept cookies as the default setting. You can modify your browser setting to reject our cookies or to prompt you before accepting a cookie by editing your browser options. However, if a browser is set not to accept cookies or if a user rejects a cookie, some portions of the Web site and services may not function properly. For example, you may not be able to sign in and access certain Web page features or services. A Web beacon is an electronic image, also called a “gif,” that may be used on our Web pages to deliver cookies, count visits and compile statistics on usage and campaign effectiveness or in our emails to tell if an email has been opened and acted upon.<br />
                <h3>Use of Personal Information</h3>
                In general, we use your personal information to process your requests or transactions, to provide you with information or services you request, to inform you about other information, events, promotions, products or services we think will be of interest to you, to facilitate your use of, and our administration and operation of, the Site and services and to otherwise serve you and our users. For example, we may use your personal information:<br />
                - to request feedback and to enable us to develop, customize and improve the Web site and our publications, products and services;
                - to conduct marketing analysis, to send you surveys or newsletters, to contact you about services, products, activities, special events or offers from CombineSell or our partners and for other marketing, informational, product development and promotional purposes;
                - to send you a welcoming email and to contact you about your use of the Site and services; to respond to your emails, submissions, comments, requests or complaints; to perform after-sales services; to anticipate and resolve problems with our service; to respond to customer support inquiries, for assistance with our product and service development; and to inform you of updates to products and services from CombineSell that better meet your needs;
                - to send and receive order and inventory information from third-party websites in which you have an account for the purposes of the services of our Site;
                - to contact you if you win a contest; and
                - for other purposes about which we notify you.<br />
                CombineSell may store and process personal information in the Singapore and other countries.<br />
                <h3>Sharing of Personal Information</h3>
                CombineSell reserves the right to share aggregated demographic information about our customers, sales, and traffic to our partners and advertisers. We will not give, sell, rent, share, or trade any of your personal information or any data that you store using our services to any third party except as outlined in this Policy or with your consent. We may disclose information to a third party to (a) comply with laws or respond to lawful requests and legal process, (b) to protect CombineSell, agents, customers, and others including to enforce our agreements, policies and terms of use or (c) in the good faith belief that disclosure is needed to respond to an emergency, or protect the personal safety of any person.<br />
                CombineSell provides you with opportunities to connect with third party services and includes product features that by their nature share information with those third party services. Those services can see your merchant order information, inventory information and counts, shipment tracking numbers and other related information. If you choose to use any such third party services, we may facilitate sharing of your information with those services. Your use of such services is not governed by CombineSell’s terms or this Policy. CombineSell does not control the services of those third parties or how they use your information and documents. Be sure to review the terms and the privacy policies of those third parties before using their services.<br />
                We may share personal information in connection with an acquisition, merger, or sale of all or a substantial portion of our business, with or to another company. In any such event, you will receive notice if your data is transferred and becomes subject to a substantially different privacy policy.<br />
                You may update, correct, or delete your Personal Data and preferences at any time by request to us at the email below. Please note that while any changes you make will be reflected in active user databases instantly or within a reasonable period of time, we may retain all information you submit for backups, archiving, prevention of fraud and abuse, analytics, satisfaction of legal obligations, or where we otherwise reasonably believe that we have a legitimate reason to do so.<br />
                You may decline to share certain Personal Data with us, in which case we may not be able to provide to you some of the features and functionality of the Services.<br />
                At any time, you may object to the processing of your Personal Data, on legitimate grounds, except if otherwise permitted by applicable law. If you believe your right to privacy granted by applicable data protection laws has been infringed upon, please contact us at the email below. You also have a right to lodge a complaint with data protection authorities.<br />
                <h3>Legal Basis for Processing Personal Data; Retention</h3>
                As before, we will only collect and use Personal Data when we have lawful bases for doing so. These lawful bases include when you provide consent, when we have a contractual obligation to collect or process your Personal Data, and when we have a legitimate interest in processing your Personal Data.<br />
                When we collect Personal Data, we keep it for as long as we need it for the purpose it is being processed for. For example, we will retain your email address information for as long as the Services are active and as needed to provide you the Services; and after that, we will keep the Personal Data for a period which enables us to handle or respond to any complaints, queries or concerns relating to your use of the Services. We will periodically review the Personal Data we hold and delete it securely when there is no longer a legal, business, or consumer need for it to be retained.<br />
                <h3>International Transfers</h3>
                Where we transfer your Personal Data outside the Singapore, we takes steps to ensure these transfers are conducted in accordance with applicable laws and using adequate and appropriate safeguards.<br />
                <h3>Network and Information Security</h3>
                CombineSell takes reasonable steps to protect information we collect from you to prevent loss, misuse and unauthorized access, disclosure, alteration, and destruction. In addition, highly confidential personal information such as credit card number and password that we request from you on our Site is protected with encryption, such as Secured Socket Layer (SSL) protocol, during transmission over the Internet.<br />
                The servers on which information is stored are kept in a controlled environment with limited access. While we take reasonable efforts to guard personal information we knowingly collect directly from you, no security system is impenetrable. In addition, we cannot guarantee that any passively-collected personal information you choose to store on our systems are maintained at adequate levels of protection to meet specific needs or obligations you may have relating to that information.<br />
                Your account information and access to our service is accessible only through the use of an individual user ID and password. To protect the confidentiality of personal information, you must keep your password confidential and not disclose it to any other person. Please advise us immediately if you believe your password has been misused. In addition, always logout and close your browser when you finish your session. Please note that we will never ask you to disclose your password in an unsolicited phone call or email.<br />
                <h3>Updating and Accessing Personal Information</h3>
                If your personal information changes in any way, we invite you to correct or update your information as soon as possible. You can make updates to your profile information by logging into your account on CombineSell at any time.<br />
                <h3>Choice/Opt-Out</h3>
                CombineSell may send you communications or data regarding our Site and services, including but not limited to (i) notices about your use of our Site and services, including any notices concerning violations of use, (ii) updates, and (iii) promotional information and materials regarding our products and services. You may opt-out of receiving promotional emails from CombineSell by following the opt-out instructions provided in those emails. Opt-out requests will not apply to transactional service messages, such as security alerts and notices about your current account and services.<br />
                <h3>‘Do Not Track’ notifications.</h3>
                Some browsers allow you to automatically notify websites you visit not to track you using a “Do Not Track” signal. There is no consensus among industry participants as to what “Do Not Track” means in this context. Like many websites and online services, we currently do not alter our practices when we receive a “Do Not Track” signal from a visitor’s browser.<br />

                <h3>Age restrictions.</h3>
                Our Services are available for purchase only for those over the age of 18. Our Services are not targeted to, intended to be consumed by or designed to entice individuals under the age of 18. If you know of or have reason to believe anyone under the age of 18 has provided us with any personal data, please contact us.<br />
                <h3>Changes in our Privacy Policy.</h3>
                We reserve the right to modify this Privacy Policy at any time. If we decide to change our Privacy Policy, we will post those changes to this Privacy Policy and any other places we deem appropriate, so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we disclose it. If we make material changes to this Privacy Policy, we will notify you here, by email, or by means of a notice on our home page, at least thirty (30) days prior to the implementation of the changes.<br />
                <h3>Data Protection Authority.</h3>
                If you are a resident of the Singapore and believe we maintain your personal data subject to the Personal Data Protection Act (PDPA).<br />
                <h3>Contact us.</h3>
                If you have any privacy-related questions, concerns or complaints about our Privacy Policy, our practices or our Services, you may contact our Office of the DPO by email at info@combinesell.com.<br />
                <strong>We will respond to all requests, inquiries or concerns within thirty (30) days.</strong>
            </div>
        </div>
    </div>
@endsection
