@extends('layouts.app')

@section('head')
    <style>
        h2 {
            margin-top: 30px;
            margin-bottom: 0;
        }
    </style>
@endsection

@section('content')
    <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
        <div class="separator separator-bottom separator-skew zindex-100">
            <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
                <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
            </svg>
        </div>
    </div>
    <!-- Page content -->
    <div class="container mt--8 pb-5">
        <div class="card bg-secondary border-0 mb-0">
            <div class="card-body px-lg-5 py-lg-5" style="white-space: pre-line;">
                <h1>Terms of Service</h1>
                Welcome to CombineSell. The CombineSell branded and related services are provided by CombineSell Pte Ltd, a Singapore private limited company (“CombineSell”) through the CombineSell Website (the “Site”) https://www.CombineSell.com and/or https://app.CombineSell.com to you (“you” or “User”). This Terms of Service Agreement (“Agreement”) is entered into by and between CombineSell and you, and is made effective as of the date of your use of this website or the date of electronic acceptance.<br />
                By using this Site, the services available at this Site, and any service, software, application, plug- in, component, functionality, or program created by CombineSell (together, the “Services”), you are agreeing to the following terms and conditions of the Agreement and Privacy Policy (“Privacy Policy”). This Agreement, along with any other policies or guidelines posted on this Site, shall govern your use of this Site and the Services, whether directly or through a third-party site. Please read them carefully before using this Site or the Services.<br />
                The terms “we”, “us” or “our” shall refer to CombineSell. The terms “you”, “your”, “User” or “customer” shall refer to any individual or entity who accepts this Agreement, has access to your account or uses the Services. Nothing in this Agreement shall be deemed to confer any third-party rights or benefits.<br />
                By visiting this Site and/or by completing the registration process for the Services, you represent and warrant that you have read, understand, have the legal capacity to, and hereby agree to be legally bound by this Agreement.<br />
                By using this Site or the Services, you represent and warrant that you are (i) at least eighteen (18) years of age, (ii) otherwise recognized as being able to form legally binding contracts under applicable law, or (iii) are not a person barred from purchasing or receiving the Services found under the laws of the Singapore or other applicable jurisdiction.<br />
                If you are entering into this Agreement on behalf of a corporate entity, you represent and warrant that you have the legal authority to bind such corporate entity to the terms and conditions contained in this Agreement, in which case the terms “you”, “your”, “User” or “customer” shall refer to such corporate entity. If, after your electronic acceptance of this<br />
                Agreement, CombineSell finds that you do not have the legal authority to bind such corporate entity, you will be personally responsible for the obligations contained in this Agreement, including, but not limited to, the payment obligations. CombineSell shall not be liable for any loss or damage resulting from CombineSell’s reliance on any instruction, notice, document or communication reasonably believed by CombineSell to be genuine and originating from an authorized representative of your corporate entity. If there is reasonable doubt about the authenticity of any such instruction, notice, document or communication, CombineSell reserves the right (but undertakes no duty) to require additional authentication from you. You further agree to be bound by the terms of this Agreement for transactions entered into by you, anyone acting as your agent and anyone who uses your account or the Services, whether or not authorized by you.<br />
                <h2>2. MODIFICATION OF AGREEMENT, SITE, OR SERVICES</h2>
                CombineSell may, in its sole and absolute discretion, change or modify this Agreement at any time, and such changes or modifications shall be effective immediately upon posting on the Site. Your use of the Services after such changes or modifications have been made shall constitute your acceptance of this Agreement as last revised. If you do not agree to be bound by this Agreement as last revised, do not use (or continue to use) the Services. It is therefore very important that you keep your Account information current. CombineSell assumes no liability or responsibility for your failure to receive an email notification if such failure results from an inaccurate email address. In addition, CombineSell may terminate your use of Services for any violation or breach of any of the terms of this Agreement by you. COMBINESELL RESERVES THE RIGHT TO MODIFY, CHANGE, OR DISCONTINUE ANY ASPECT OF THIS SITE OR THE SERVICES, INCLUDING WITHOUT LIMITATION PRICES AND FEES FOR THE SAME, AT ANY TIME.<br />
                <h2>3. YOUR REGISTRATION OBLIGATIONS</h2>
                To obtain and use the Services, you will be required to register with CombineSell by completing a registration form and designating a user ID and password. When registering with CombineSell, you agree to: (a) provide true, accurate, current, and complete information about yourself as prompted by the Service’s registration form (such information being the “Registration Data”) and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current, or incomplete, or we have grounds to suspect that such information is untrue, inaccurate, not current, or incomplete, we may suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).<br />
                You may not authorize any third party to access or use the Services on your behalf. You are responsible for maintaining the confidentiality of the user ID and password, and solely responsible for the activity that occurs on your account, whether authorized by you or not, and you must keep your account information secure. You agree to immediately notify CombineSell of any unauthorized use of your user ID or password or any other breach of security. CombineSell cannot and will not be liable for any loss or damage arising from any unauthorized use of your account.<br />
                <h2>4. GENERAL RULES OF CONDUCT</h2>
                You acknowledge and agree that:<br />
                i. Your use of this Site and the Services, including any content you submit, will comply with this Agreement, any applicable Services Agreement or policy that may apply to your Services and all applicable local, state, national and international laws, rules and regulations.
                ii. You will not collect or harvest (or permit anyone else to collect or harvest) any User Content (as defined below) or any non-public or personally identifiable information about another User or any other person or entity without their express prior written consent.
                iii. You will not use this Site or the Services in a manner (as determined by CombineSell in its sole and absolute discretion) that:
                <ul>
                    • Is illegal, or promotes or encourages illegal activity;
                    • Promotes, encourages or engages in child pornography or the exploitation of children;
                    • Promotes, encourages or engages in terrorism, violence against people, animals, or
                    property;
                    • Promotes, encourages or engages in any spam or other unsolicited bulk email, or
                    computer or network hacking or cracking;
                    • Violates the Ryan Haight Online Pharmacy Consumer Protection Act of 2008 or similar
                    legislation, or promotes, encourages or engages in the sale or distribution of prescription medication without a valid prescription;
                    • Violates the Fight Online Sex Trafficking Act of 2017 or similar legislation, or promotes or facilitates prostitution and/or sex trafficking;
                    • Infringes on the intellectual property rights of another User or any other person or entity;
                    • Violates the privacy or publicity rights of another User or any other person or entity, or breaches any duty of confidentiality that you owe to another User or any other person or entity;
                    • Interferes with the operation of this Site or the Services found at this Site;
                    • Contains or installs any viruses, worms, bugs, Trojan horses or other code, files or programs designed to, or capable of, disrupting, damaging or limiting the functionality of any software or hardware; or
                    • Contains false or deceptive language, or unsubstantiated or comparative claims,
                    regarding CombineSell or CombineSell’s Services.
                </ul>
                iv. You will not copy or distribute in any medium any part of this Site or the Services, except where expressly authorized by CombineSell.
                v. You will not modify or alter any part of this Site or the Services found at this Site or any of its related technologies.
                vi. You will not access CombineSell Content (as defined below) or User Content through any technology or means other than through this Site itself, or as CombineSell may designate.
                vii. You agree to back-up all of your User Content so that you can access and use it when needed. CombineSell does not warrant that it backs-up any Account or User Content, and you agree to accept as a risk the loss of any and all of your User Content.
                viii. You will not re-sell or provide the Services for a commercial purpose, including any of CombineSell’s related technologies, without CombineSell’s express prior written consent.
                ix. You will not to circumvent, disable or otherwise interfere with the security-related features of this Site or the Services found at this Site (including without limitation those features that prevent or restrict use or copying of any CombineSell Content or User Content) or enforce limitations on the use of this Site or the Services found at this Site, the CombineSell Content or the User Content therein.
                x. You agree to provide government-issued photo identification and/or government-issued business identification as required for verification of identity when requested.
                xi. You are aware that CombineSell may from time-to-time call you about your account, and that, for the purposes of any and all such call(s), you may be subject to call recording and hereby consent to the same, subject to any applicable laws and our restrictions and obligations thereunder, including, where permissible, to record the entirety of such calls regardless of whether CombineSell asks you on any particular call for consent to record such call. You further acknowledge and agree that, to the extent permitted by applicable law, any such recording(s) may be submitted as evidence in any legal proceeding in which CombineSell is a party. Further, by providing your telephone or mobile number, you consent to receive marketing telephone calls from or on behalf of CombineSell that may be initiated by an automatic telephone dialing system and/or use an artificial or prerecorded voice. You understand that providing consent is not a condition of purchasing any good or service from CombineSell. Similarly, by providing your mobile number, you consent to receive marketing text messages from or on behalf of CombineSell that may be sent by an automatic telephone dialing system. You understand that providing consent is not a condition of purchasing any good or service from CombineSell. Message and data rates may apply.
                xii. Without limiting any of the rights set forth elsewhere in this Agreement, CombineSell expressly reserves the right to deny, cancel, terminate, suspend, or limit future access to this Site or any Services to any User (i) whose Account or Services were previously terminated or suspended, whether due to breach of this or any other Agreement or any CombineSell policy, or (ii) who otherwise engages or has engaged in inappropriate or unlawful activity while utilizing the Site or Services (as determined by CombineSell in its sole and absolute discretion).<br />
                <h2>5. USER CONTENT</h2>
                Some of the features of this Site or the Services may allow Users to view, post, publish, share, store, or manage (a) ideas, opinions, recommendations, or advice via forum posts, content submitted in connection with a contest, product reviews or recommendations, or photos to be incorporated into a social media event or activity (“User Submissions”), or (b) literary, artistic, musical, or other content, including but not limited to photos and videos (together with User Submissions, “User Content”). All content submitted through your Account is consider User Content. By posting or publishing User Content to this Site or to or via the Services, you represent and warrant to CombineSell that (i) you have all necessary rights to distribute User Content via this Site or via the Services, either because you are the author of the User Content and have the right to distribute the same, or because you have the appropriate distribution rights, licenses, consents, and/or permissions to use, in writing, from the copyright or other owner of the User Content, and (ii) the User Content does not violate the rights of any third party. You shall be solely responsible for any and all of your User Content or User Content that is submitted through your Account, and the consequences of, and requirements for, distributing it.<br />
                <em>User Submissions</em>. You acknowledge and agree that your User Submissions are entirely voluntary, do not establish a confidential relationship or obligate CombineSell to treat your User Submissions as confidential or secret, that CombineSell has no obligation, either express or implied, to develop or use your User Submissions, and no compensation is due to you or to anyone else for any intentional or unintentional use of your User Submissions, and that CombineSell may be working on the same or similar content, it may already know of such content from other sources, it may simply wish to develop this (or similar) content on its own, or it may have taken / will take some other action.<br />
                CombineSell shall own exclusive rights (including all intellectual property and other proprietary rights) to any User Submissions posted to this Site, and shall be entitled to the unrestricted use and dissemination of any User Submissions posted to this Site for any purpose, commercial or otherwise, without acknowledgment or compensation to you or to anyone else.<br />
                User Content Other Than User Submissions. To the extent that the Services provide Users an opportunity to retrieve and send inventory and order information from User’s marketplace accounts, you hereby represent and warrant that you have all necessary rights in and to all User Content you provide and all information contained therein. By registering to use the Services, you understand and acknowledge that CombineSell and its contractors retain an irrevocable, royalty-free, worldwide license to use, copy, and publicly display such content for the sole purpose of providing to you the Services for which you have registered. In the event that you give CombineSell the right to distribute your content, additional terms may apply to CombineSell’s usage or distribution of this content. You continue to retain all ownership rights in any User Content you provide and shall remain solely responsible for your conduct, your User Content, and any material or information transmitted to other Users for interaction with other Users. CombineSell does not claim any ownership rights in any User Content.<br />
                By posting or publishing User Content to this Site or through the Services, you authorize CombineSell to use the intellectual property and other proprietary rights in and to your User Content to enable inclusion and use of the User Content in the manner contemplated by this Site and this Agreement. You hereby grant CombineSell a worldwide, non-exclusive, royalty- free, sublicensable (through multiple tiers), and transferable license to use, reproduce, distribute, prepare derivative works of, combine with other works, display, and perform your User Content in connection with this Site, the Services and CombineSell’s (and CombineSell’s affiliates’) business(es), including without limitation for promoting and redistributing all or part of this Site in any media formats and through any media channels without restrictions of any kind and without payment or other consideration of any kind, or permission or notification, to you or any third party. You also hereby grant each User of this Site a non-exclusive license to access your User Content (with the exception of User Content that you designate “private” or “password protected”) through this Site, and to use, reproduce, distribute, prepare derivative works of, combine with other works, display, and perform your User Content as permitted through the functionality of this Site and under this Agreement. The above licenses granted by you in your User Content terminate within a commercially reasonable time after you remove or delete your User Content from this Site. You understand and agree, however, that CombineSell may retain (but not distribute, display, or perform) server copies of your User Content that have been removed or deleted. The above licenses granted by you in your User Content are perpetual and irrevocable. Notwithstanding anything to the contrary contained herein, CombineSell shall not use any User Content that has been designated “private” or “password protected” by you for the purpose of promoting this Site or CombineSell’s (or CombineSell’s affiliates’) business(es). If you have a website or other content hosted by CombineSell, you shall retain all of your ownership or licensed rights in User Content.<br />
                <h2>6. AVAILABILITY OF WEBSITE/SERVICES</h2>
                Subject to the terms and conditions of this Agreement and our other policies and procedures, we shall use commercially reasonable efforts to attempt to provide this Site and the Services on a twenty-four (24) hours a day, seven (7) days a week basis. You acknowledge and agree that from time to time this Site may be inaccessible or inoperable for any reason including, but not limited to, equipment malfunctions; periodic maintenance, repairs or replacements that we undertake from time to time; or causes beyond our reasonable control or that are not reasonably foreseeable including, but not limited to, interruption or failure of telecommunication or digital transmission links, hostile network attacks, network congestion or other failures. You acknowledge and agree that we have no control over the availability of this Site or the Service on a continuous or uninterrupted basis, and that we assume no liability to you or any other party with regard thereto.<br />
                <h2>7. MONITORING OF CONTENT; ACCOUNT TERMINATION POLICY</h2>
                CombineSell generally does not pre-screen User Content. However, CombineSell reserves the right (but undertakes no duty) to do so and decide whether any item of User Content is appropriate and/or complies with this Agreement. CombineSell may remove any item of User Content and/or terminate a User’s access to this Site or the Services found at this Site for posting or publishing any material in violation of this Agreement, or for otherwise violating this Agreement (as determined by CombineSell in its sole and absolute discretion), at any time and without prior notice. CombineSell may also terminate a User’s access to this Site or the Services found at this Site if CombineSell has reason to believe the User is a repeat offender. If CombineSell terminates your access to this Site or the Services found at this Site, CombineSell may, in its sole and absolute discretion, remove and destroy any data and files stored by you on its servers.
                <h2>8. DISCONTINUED SERVICES; END OF LIFE POLICY</h2>
                CombineSell reserves the right to cease offering or providing any of the Services at any time, for any or no reason, and without prior notice. Although CombineSell makes great effort to maximize the lifespan of all its Services, there are times when a Service we offer will be discontinued or reach its End-of-Life (“EOL”). If that is the case, that product or service will no longer be supported by CombineSell, in any way, effective on the EOL date.<br />
                Notice and Migration. In the event that any Service we offer has reached or will reach EOL, we will attempt to notify you thirty or more days in advance of the EOL date. It is your responsibility to take all necessary steps to replace the Service by migrating to a new Service before the EOL date, or by entirely ceasing reliance on said Service before the EOL date. In either case, CombineSell will either offer a comparable Service for you to migrate to for the remainder of the term of your purchase, a prorated in-store credit, or a prorated refund, to be determined by<br />
                CombineSell in its sole and absolute discretion. CombineSell may, with or without notice to you, migrate you to the most up-to-date version of the Service, if available. You agree to take full responsibility for any and all loss or damage arising from any such migration.<br />
                No Liability. CombineSell will not be liable to you or any third party for any modification, suspension, or discontinuance of any of the Services we may offer or facilitate access to.<br />
                <h2>9. TRADEMARK AND/OR COPYRIGHT CLAIMS</h2>
                CombineSell supports the protection of intellectual property. If you would like to submit (i) a trademark claim for violation of a mark on which you hold a valid, registered trademark or service mark, or (ii) a copyright claim for material on which you hold a bona fide copyright, please refer to our Trademark and/or Copyright Infringement Policy referenced above and available in our TRADEMARK/COPYRIGHT INFRINGEMENT document.<br />
                <h2>10. THIRD PARTY CONTENT, SITES, AND SERVICES</h2>
                All transactions using CombineSell’s services are between the transacting parties only. The Services may contain features and functionalities linking you or providing you with certain functionality and access to third party content, including websites, directories, servers, networks, systems, information and databases, applications, software, programs, products or services, and the Internet as a whole. We may also provide some content to you as part of the Services. However, CombineSell is not an agent of any transacting party, nor are we a direct party in any such transaction. Any such activities, and any terms associated with such activities, are solely between you and the applicable third-party. Similarly, we are not responsible for any third-party content you access with the Services, and you irrevocably waive any claim against us with respect to such sites and third-party content. CombineSell shall have no liability, obligation, or responsibility for any such correspondence, purchase, or promotion between you and any such third-party. You are solely responsible for investigating before proceeding with any online or offline transaction with any third party. You are solely responsible for your dealings with any third party related to the Services, including the delivery of and payment for goods and services. Should you have any problems resulting from your use of any third-party services, or should you suffer data loss or other losses as a result of problems with any of your other service providers or any third-party services, we disclaim all liability.<br />

                <h2>11. FEES AND PAYMENTS; AUTOMATIC RENEWAL</h2>
                The fees applicable for CombineSell service are available at www.CombineSell.com and as published within the Services.<br />
                Unless specifically agreed upon in writing between User and CombineSell at the commencement of a subscription term, at the conclusion of any service term, whether monthly, yearly, or otherwise, CombineSell will automatically renew the service for the same term and will charge the user’s credit card or PayPal account on the first day of the renewal term.<br />
                Payments for all single-seat accounts are due within 30 days of billing date. The last day of the 14-day trial signifies the due date of first payment.<br />
                If payment is not received by the end of the given 30 day time period, user’s account will be frozen and inaccessible until all outstanding payments have been processed by CombineSell. Users retain the responsibility for settling all outstanding balances in a timely manner and maintaining updated billing information. If not complied with, at the end of 90 days, user’s account will be deactivated and all data will no longer be retrievable.<br />
                Price Changes. CombineSell reserves the right to change its prices and fees at any time, and such changes shall be posted online at this Site and effective immediately without need for further notice to you. If you have purchased or obtained Services for a period of months or years, changes in prices and fees shall be effective when the Services in question come up for renewal as further described below.
                Auto-Renewal Terms. In order to ensure that you do not experience an interruption or loss of Services, all Services are offered on automatic renewal. Except for reasons described below in this section, automatic renewal automatically renews the applicable Service upon expiration of the then current term for a renewal period equal in time to the most recent service period. For example, if your last service period is for one year, your renewal period will typically be for one year. However, in the event renewal with the Payment Method on file fails, COMBINESELL may attempt to renew the applicable service for a period less than the original subscription period to the extent necessary for the transaction to succeed.<br />
                Unless you disable the automatic renewal option, COMBINESELL will automatically renew the applicable Service when it comes up for renewal and will take payment from any Payment Method you have on file with COMBINESELL at COMBINESELL’S then current rates, which you acknowledge and agree may be higher or lower than the rates for the original service period. If you do not wish for any Service to automatically renew, you may elect to cancel renewal, in which case, your Services will terminate upon expiration of the then current term, unless you manually renew your Services prior to that date (in which case the Services will again be set to automatic renewal). In other words, should you elect to cancel your product and fail to manually renew your Services before they expire, you may experience an interruption or loss of Services, and COMBINESELL shall not be liable to you or any third party regarding the same.<br />
                <h2>12. ADDITIONAL RESERVATION OF RIGHTS</h2>
                CombineSell expressly reserves the right to deny, cancel, terminate, suspend, lock, or modify access to (or control of) any Account or Services for any reason (as determined by CombineSell in its sole and absolute discretion), including but not limited to the following: (i) to correct mistakes made by CombineSell in offering or delivering any Services, (ii) to protect the integrity and stability of, and correct mistakes made by, any third party (iii) to assist with our fraud and abuse detection and prevention efforts, (iv) to comply with court orders against you and/or your domain name or website and applicable local, state, national and international laws, rules and regulations, (v) to comply with requests of law enforcement, including subpoena requests, (vi) to comply with any dispute resolution process, (vii) to defend any legal action or threatened legal action without consideration for whether such legal action or threatened legal action is eventually determined to be with or without merit, (viii) to avoid any civil or criminal liability on the part of CombineSell, its officers, directors, employees and agents, as well as CombineSell’s affiliates, including, but not limited to, instances where you have sued or threatened to sue CombineSell, or (ix) to respond to an excessive amount of complaints related in any way to your Account, domain name(s), or content on your website that could result in damage to CombineSell’s business, operations, reputation or shareholders.<br />
                CombineSell expressly reserves the right to review every Account for excessive space and bandwidth utilization, and to terminate or apply additional fees to those Accounts that exceed allowed levels.<br />
                CombineSell expressly reserves the right to terminate, without notice to you, any and all Services where, in CombineSell’s sole discretion, you are harassing or threatening CombineSell and/or any of CombineSell’s employees.<br />
                CombineSell Content. Except for User Content, the content on this Site and the Services, including without limitation the text, software, scripts, source code, API, graphics, photos, sounds, music, videos and interactive features and the trademarks, service marks and logos contained therein (“CombineSell Content”), are owned by or licensed to CombineSell in perpetuity, and are subject to copyright, trademark, and/or patent protection in the Singapore and foreign countries, and other intellectual property rights under Singapore and foreign laws. CombineSell Content is provided to you “as is”, “as available” and “with all faults” for your information and personal, non-commercial use only and may not be downloaded, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any purposes whatsoever without the express prior written consent of CombineSell. No right or license under any copyright, trademark, patent, or other proprietary right or license is granted by this Agreement. CombineSell reserves all rights not expressly granted in and to the CombineSell Content, this Site and the Services, and this Agreement do not transfer ownership of any of these rights.<br />
                <h2>13. REFUND OF CHARGES</h2>
                Except as specifically set forth in this section, all Services are prepaid for the period selected (monthly, yearly or otherwise) and are non-refundable. CombineSell does not provide refunds or rebates on the Services, pro-rated or otherwise.<br />
                Users on free 14-day trial may cancel or downgrade their accounts, free of charge, at any time up until fourteen(14) days after their account was created. The day of creation constitutes the first day of the 14-day trial.<br />
                All cancellations and downgrades are processed automatically. To cancel or downgrade, please click the link or button that says “Cancel” and follow the instructions.<br />
                If you have a question while canceling your account, you must give our email staff adequate time to respond to your message. Delays in our support system do not qualify as a reason to extend your trial period, or excuse canceling after 14 days. Cancellation requests sent via email to support@CombineSell.com will not be processed and will be replied to with an automatic response. You must use our form to process your cancellation.<br />
                <h2>14. LINKS TO THIRD-PARTY WEBSITES</h2>
                This Site and the Services found at this Site may contain links to third-party websites that are not owned or controlled by CombineSell. CombineSell assumes no responsibility for the content, terms and conditions, privacy policies, or practices of any third-party websites. In addition, CombineSell does not censor or edit the content of any third-party websites. By using this Site or the Services found at this Site, you expressly release CombineSell from any and all liability arising from your use of any third-party website. Accordingly, CombineSell encourages you to be aware when you leave this Site or the Services found at this Site and to review the terms and conditions, privacy policies, and other governing documents of each other website that you may visit.<br />
                <h2>15. DISCLAIMER OF REPRESENTATIONS AND WARRANTIES</h2>
                YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT YOUR USE OF THIS SITE AND THE SERVICES FOUND AT THIS SITE SHALL BE AT YOUR OWN RISK AND THAT THIS SITE AND THE SERVICES FOUND AT THIS SITE ARE PROVIDED “AS IS”, “AS AVAILABLE” AND “WITH ALL FAULTS”. COMBINESELL, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND ALL THIRD PARTY SERVICE PROVIDERS DISCLAIM ALL WARRANTIES, STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. COMBINESELL, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS MAKE NO REPRESENTATIONS OR WARRANTIES ABOUT (I) THE ACCURACY, COMPLETENESS, OR CONTENT OF THIS SITE, (II) THE ACCURACY, COMPLETENESS, OR CONTENT OF ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, AND/OR (III) THE SERVICES FOUND AT THIS SITE OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, AND COMBINESELL ASSUMES NO LIABILITY OR RESPONSIBILITY FOR THE SAME.<br />
                IN ADDITION, YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT NO ORAL OR WRITTEN INFORMATION OR ADVICE PROVIDED BY COMBINESELL, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS (INCLUDING WITHOUT LIMITATION ITS CALL CENTER OR CUSTOMER SERVICE REPRESENTATIVES), AND THIRD PARTY SERVICE PROVIDERS WILL (I) CONSTITUTE LEGAL OR FINANCIAL ADVICE OR (II) CREATE A WARRANTY OF ANY KIND WITH RESPECT TO THIS SITE OR THE SERVICES FOUND AT THIS SITE, AND USERS SHOULD NOT RELY ON ANY SUCH INFORMATION OR ADVICE.<br />
                THE FOREGOING DISCLAIMER OF REPRESENTATIONS AND WARRANTIES SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW, AND shall survive any termination or expiration of this Agreement or your use of this Site or the Services found at this Site.<br />
                <h2>16. LIMITATION OF LIABILITY</h2>
                IN NO EVENT SHALL COMBINESELL, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND ALL THIRD PARTY SERVICE PROVIDERS, BE LIABLE TO YOU OR ANY OTHER PERSON OR ENTITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING ANY THAT MAY RESULT FROM (I) THE ACCURACY, COMPLETENESS, OR CONTENT OF THIS SITE, (II) THE ACCURACY, COMPLETENESS, OR CONTENT OF ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (III) THE SERVICES FOUND AT THIS SITE OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (IV) PERSONAL INJURY OR PROPERTY DAMAGE OF ANY NATURE WHATSOEVER, (V) THIRD-PARTY CONDUCT OF ANY NATURE WHATSOEVER, (VI) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY AND ALL CONTENT, PERSONAL INFORMATION, FINANCIAL INFORMATION OR OTHER INFORMATION AND DATA STORED THEREIN, (VII) ANY INTERRUPTION OR CESSATION OF SERVICES TO OR FROM THIS SITE OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (VIII) ANY VIRUSES, WORMS, BUGS, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR FROM THIS SITE OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (IX) ANY USER CONTENT OR CONTENT THAT IS DEFAMATORY, HARASSING, ABUSIVE, HARMFUL TO MINORS OR ANY PROTECTED CLASS, PORNOGRAPHIC, “X-RATED”, OBSCENE OR OTHERWISE OBJECTIONABLE, AND/OR (X) ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF THIS SITE OR THE SERVICES FOUND AT THIS SITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL OR EQUITABLE THEORY, AND WHETHER OR NOT COMBINESELL IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                <br />
                IN ADDITION, You SPECIFICALLY ACKNOWLEDGE AND agree that in no event shall COMBINESELL’S total aggregate liability exceed $1,000.00 S.G. Dollars.<br />
                THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW, AND shall survive any termination or expiration of this Agreement or your use of this Site or the Services found at this Site.<br />
                <h2>17. INDEMNITY</h2>
                You agree to protect, defend, indemnify and hold harmless CombineSell and its officers, directors, employees, agents, and third party service providers from and against any and all claims, demands, costs, expenses, losses, liabilities and damages of every kind and nature (including, without limitation, reasonable attorneys’ fees) imposed upon or incurred by CombineSell directly or indirectly arising from (i) your use of and access to this Site or the Services found at this Site; (ii) your violation of any provision of this Agreement or the policies or agreements which are incorporated herein; and/or (iii) your violation of any third-party right, including without limitation any intellectual property or other proprietary right. The indemnification obligations under this section shall survive any termination or expiration of this Agreement or your use of this Site or the Services found at this Site.<br />
                <h2>18. COMPLIANCE WITH LOCAL LAWS</h2>
                CombineSell makes no representation or warranty that the content available on this Site or the Services found at this Site are appropriate in every country or jurisdiction, and access to this Site or the Services found at this Site from countries or jurisdictions where its content is illegal is prohibited. Users who choose to access this Site or the Services found at this Site are responsible for compliance with all local laws, rules and regulations.<br />
                <h2>19. SUCCESSORS AND ASSIGNS</h2>
                This Agreement shall be binding upon and inure to the benefit of the parties hereto and their respective heirs, successors and assigns.<br />
                <h2>20. NO THIRD-PARTY BENEFICIARIES</h2>
                Nothing in this Agreement shall be deemed to confer any third-party rights or benefits.<br />
                <h2>21. TITLES AND HEADINGS; INDEPENDENT COVENANTS; SEVERABILITY</h2>
                The titles and headings of this Agreement are for convenience and ease of reference only and shall not be utilized in any way to construe or interpret the agreement of the parties as otherwise set forth herein. Each covenant and agreement in this Agreement shall be construed for all purposes to be a separate and independent covenant or agreement. If a court of competent jurisdiction holds any provision (or portion of a provision) of this Agreement to be illegal, invalid, or otherwise unenforceable, the remaining provisions (or portions of provisions) of this Agreement shall not be affected thereby and shall be found to be valid and enforceable to the fullest extent permitted by law.<br />
                <h2>22. ENGLISH LANGUAGE CONTROLS</h2>
                This Agreement, along with all policies and the applicable product agreements identified above and incorporated herein by reference (collectively, the “Agreement”), is executed in the English language. To the extent any translation is provided to you, it is provided for convenience purposes only, and in the event of any conflict between the English and translated version, where permitted by law, the English version will control and prevail. Where the translated version is required to be provided to you and is to be considered binding by law (i) both language versions shall have equal validity, (ii) each party acknowledges that it has reviewed both language versions and that they are substantially the same in all material respects, and (iii) in the event of any discrepancy between these two versions, the translated version may prevail, provided that the intent of the Parties has been fully taken into consideration.<br />
                <h2>23. CONTACT INFORMATION</h2>
                If you have any questions about this Agreement, please contact us by email or regular mail at the following address:<br />
                CombineSell Legal Department
                22 Changi Business Park Central 2,<br /> #02-08 The Kingsmen Experience, <br />Singapore 486032.<br /> info@combinesell.com
            </div>
        </div>
    </div>
@endsection